### ISSUE TITLE
travis build for mono 3.12 and 3.10 run into error 

### ISSUE THREAD

**Issue by rferstl** [ferronrsmith/httpcontext-simulator#14]
Hi Ferron,
I try to send a pull request but the travis build for mono 3.12 and 3.10 run into errors.
Also without any changes to current master brunch, does it work on your side?

`Target CoreCompile:
				Tool /usr/lib/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug:pdbonly /optimize+ /out:obj/Release/HttpSimulator.dll BaseWrapped/HttpSessionState.cs BaseWrapped/HttpContext.cs HttpSimulator.cs IHttpContext.cs IHttpRequest.cs IHttpResponse.cs IHttpServerUtility.cs Properties/AssemblyInfo.cs ReflectionHelper.cs SimulatedHttpRequest.cs BaseWrapped/SimulatedHttpRequest.cs BaseWrapped/HttpServerUtility.cs obj/Release/.NETFramework,Version=v4.0.AssemblyAttribute.cs /target:library /define:TRACE /nostdlib /reference:/usr/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll /reference:/usr/lib/mono/gac/System.Web/4.0.0.0__b03f5f7f11d50a3a/System.Web.dll /reference:/usr/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll /warn:4
CSC: error CS0518: The predefined type System.Object is not defined or imported
CSC: error CS0518: The predefined type System.ValueType is not defined or imported
CSC: error CS0518: The predefined type System.Attribute is not defined or imported ...`

Best regards Roland

**Comment by ferronrsmith** [comment]
resolved in #16
