### ISSUE TITLE
Information license

### ISSUE THREAD

**Issue by villers** [ferronrsmith/httpcontext-simulator#6]
Hello,

i see the nuget package is under GPL License and the based source is under MIT License.

What is the real License?

![image](https://cloud.githubusercontent.com/assets/3822295/20000635/c4f68778-a278-11e6-9d6a-159dc34cd551.png)

Cordially,
VILLERS M.

**Comment by ferronrsmith** [comment]
What happen was, I am not the owner of the github package. The original nuget creator used the GPL 2.0 license while Github source was license under MIT.. I will change the source to match nuget repository. apologies for the inconvenience.

**Comment by villers** [comment]
Thank you :)
