### ISSUE TITLE
HttpSimulator is not a strongly-Named assembly

### ISSUE THREAD

**Issue by xvimaluenda** [ferronrsmith/httpcontext-simulator#9]
Hello,

We are using your assembly in the Unitary Tests (UT) of one our company projects for a long time but we are having some problems now because we are strongly-naming our assemblies (we use still .Net framework) and an exceptiong raise (saying that your assembly is not a strongly-named one) when we try to run those UT....

There is any way that you fix it?

Best regards

**Comment by ferronrsmith** [comment]
Feel free to submit a PR and I'll merge it.

**Comment by robdmoore** [comment]
Putting aside the fact that strong naming is pointless in most instances for your main code, why would you strong name your unit tests?

More info: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

--

**Comment by ferronrsmith** [comment]
I was thinking the same thing ... Seems pointless to me for a library that used only for testing.

**Comment by xvimaluenda** [comment]
Hi,

I agree that strong naming could be pointless the problem, for us, is that our Unit test assemblies are strong named too (this a legacy app and there are truth relations beetwen functional and unit test assemblies) and ... strong named assemblies can only reference others strong named assemblies.... :(

In any case, and it is just a personal opinion, as far as converting your assembly to strong naming doesn't carry any issue for you (your own Unit testing process, ...) it would be beneficious for the adoption of your assembly because even if your assembly becomes strong named it won't be a problem for any existing "weak" named assembly reference it....

Thnks
(P.S.: I apologize for my poor english... It is not my main tongue and I'm not used to use it....)
